Output demo.gif

Set FontSize 16
Set Width 1200
Set Height 700
Set Margin 10
Set MarginFill "#fff955"

Type "fileport"
Sleep 500ms
Enter

Sleep 3s

Type "fileport help"
Sleep 500ms
Enter

Sleep 3s

Type "fileport status"
Sleep 500ms
Enter

Sleep 3s

Type "fileport list -r"
Sleep 500ms
Enter

Sleep 3s

Type "ls"
Sleep 500ms
Enter

Sleep 3s

Type "fileport get more-testing/demo.gif"
Sleep 500ms
Enter

Sleep 3s

Type "ls"
Sleep 500ms
Enter

Sleep 5s
